# Generated by Django 2.1.2 on 2018-12-17 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='event_image')),
                ('topics', models.TextField(blank=True, null=True)),
                ('max_part_stud', models.PositiveIntegerField(default=2)),
                ('time', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=20)),
                ('rules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('member_name', models.CharField(max_length=50)),
                ('member_name2', models.CharField(max_length=50)),
                ('college', models.TextField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
